### ISSUE TITLE
"PUPPETEER_SKIP_DOWNLOAD"

### ISSUE THREAD

**Issue by mamalli11** [frinyvonnick/node-html-to-image#108]
ERROR: Failed to set up Chromium r737027! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/737027/chrome-win.zip

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by frinyvonnick** [comment]
I released a new version of node-html-to-image (3.2.0) that updates puppeteer version which might fix your issue. Could you give it a try and close the issue if it fixes your problem?

**Comment by mamalli11** [comment]
Thank you for following up and resolving this issue 👌🏻👍🏻

**Comment by frinyvonnick** [comment]
Your welcome! I close the issue then 😁
