### ISSUE TITLE
@font-face doesn't work

### ISSUE THREAD

**Issue by Izers** [frinyvonnick/node-html-to-image#115]
When I run my html code the custom fonts are working but when I use nodeHtmlToImage() the fonts are not loaded

![image](https://user-images.githubusercontent.com/50419381/122673116-45896600-d1cf-11eb-8278-8ba168ab0348.png)

![image](https://user-images.githubusercontent.com/50419381/122673168-8c775b80-d1cf-11eb-9bde-9d9b5d0cd192.png)

**Comment by frinyvonnick** [comment]
Hello @Izers 👋 

I just merged a [piece of documentation](https://github.com/frinyvonnick/node-html-to-image#dealing-with-images) on this topic. Does it help you fix your problem?

**Comment by ElijahGives** [comment]
stop discord scamming mf

**Comment by frinyvonnick** [comment]
@ElijahGives I assume that "mf" is an insult (see [definition](https://www.urbandictionary.com/define.php?term=MF)). I would like you to be more polite as asked in the [code of conduct](https://github.com/frinyvonnick/node-html-to-image/blob/master/CODE_OF_CONDUCT.md).

**Comment by frinyvonnick** [comment]
I close this issue since I did not get any answer for a long time and there is a section in the README that explains how to deal with it.
