### ISSUE TITLE
Empty white image when using another image.

### ISSUE THREAD

**Issue by Lejla94** [frinyvonnick/node-html-to-image#119]
```
`const nodeHtmlToImage = require('node-html-to-image')

nodeHtmlToImage({
    output: './image.png',
    html: '<html><body><img src="./DW17-37.jpg" /></body></html>'
  })
  .then(() => console.log('The image was created successfully!'))`
```

With this code i get the white empty image.
I want to print a cropped image into another image.
Any solution or other way?

**Comment by frinyvonnick** [comment]
Hello @Lejla94 👋 

There is a dedicated section in the README that explain how to [deal with images](https://github.com/frinyvonnick/node-html-to-image#dealing-with-images). Please close this issue if it fixes your problem.
