### ISSUE TITLE
Conflict in case of instructions regarding output tag

### ISSUE THREAD

**Issue by shankha007** [frinyvonnick/node-html-to-image#12]
`const express = require('express');
const router = express.Router();
const nodeHtmlToImage = require('node-html-to-image');

router.get(`/api/tweet/render`, async function(req, res) {
  const image = await nodeHtmlToImage({
    html: '<html><body><div>Check out what I just did! #cool</div></body></html>'
  });
  res.writeHead(200, { 'Content-Type': 'image/png' });
  res.end(imgBinary, 'binary');
});`
Here in this sample, you have not given the output tag. But according to the code you mentioned that if there is no output tag it will throw error.  Then you should make the use of output tag optional.

**Comment by frinyvonnick** [comment]
Hi @shankha007 👋 

Thank you for posting this issue. Sure, this is a bug. I forgot about this error while reviewing #10. Do you want to open a pull request to make usage of output property optional?

**Comment by shankha007** [comment]
Yes, it will be helpful for me :)

**Comment by frinyvonnick** [comment]
Nice, I'm eager to review it 👍

**Comment by frinyvonnick** [comment]
👋 @shankha007 I need this before publishing a new version. Do you think you have time to do it in the next few days or should I do it myself?

**Comment by shankha007** [comment]
You better do it for now. I am little bit busy in my project...

**Comment by frinyvonnick** [comment]
Ok, no problem I understand. Maybe you could contribute later 👍

**Comment by weiyunpeng** [comment]
Has the problem been solved？

**Comment by frinyvonnick** [comment]
This was fixed in #16 and published in 2.0.0
