### ISSUE TITLE
Error pupputer 

### ISSUE THREAD

**Issue by EmersonGarrido** [frinyvonnick/node-html-to-image#121]
Every time I go to upload the application in production on the linux server ubuntu I have to set the args configuration: ["--no-sandbox"] in puppeter, would I be able to fix this in your lib?

I believe that several people are going through the same problem.

Is file index.js here lauch puppeter

**Comment by frinyvonnick** [comment]
Hello @EmersonGarrido, node-html-to-image is basically a wrapper around puppeteer to avoid writing boilerplate code. If you experience any issue with puppeteer you can find help in their [troobleshooting section](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md). There is a [specific section](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) about issues regarding sandbox on linux.

**Comment by EmersonGarrido** [comment]
A certain friend agrees that there is, but if I had an option in your code as described below, it would solve the problem.

`const {
    html,
    content,
    output,
    selector = 'body',
    puppeteerArgs = {
     args: ["--no-sandbox"],  // set Args inline 13 file index.js folder SRC  lib = node-html-to-image
    },
  } = options`

**Comment by frinyvonnick** [comment]
I don't want to set default values to puppeteerArgs since it depends on use cases (your usage, your os, maybe you are doing this on a server or cloud provider, a lot of possibilities). I don't feel it wrong you have to setup the good options for your use case in your code.

**Comment by frinyvonnick** [comment]
@EmersonGarrido you can pass the args to puppeteer using the property `puppeteerArgs `. Here is an example:

```js
const nodeHtmlToImage = require('node-html-to-image')

nodeHtmlToImage({
  output: './image.png',
  html: '<html><body>Hello world!</body></html>',
  puppeteerArgs: { args: ["--no-sandbox"] }
})
  .then(() => console.log('The image was created successfully!'))
```

It seems pretty convenient to me. Doing it this way you don't have to change node-html-to-image code each time you want to use it 🤔 . Maybe I did not understand well your problem. Could you reformulate so I understand it?

**Comment by EmersonGarrido** [comment]
What you did worked, congratulations on the project and thanks for adding this option kkk even though it took a while it was perfect.

**Comment by frinyvonnick** [comment]
This option @EmersonGarrido is available since the very first version of the library 🤔...
