### ISSUE TITLE
Using puppeteer connect instead of running the instance on same machine

### ISSUE THREAD

**Issue by Tsopic** [frinyvonnick/node-html-to-image#138]
Hey,

There are no options to use a browserless stack with the puppeteer. Packing such a heavy library by default into the server is not the best idea. 

I'm unable to find a way to pass down my puppeteer tasks over WebSocket to existing browserless.

**Comment by frinyvonnick** [comment]
Hello @Tsopic 👋 

Thank you for posting this issue 🙏  I don't understand what you are trying to achieve 🤔  Could you explain it to me more precisely?

**Comment by Tsopic** [comment]
Using websocket connection instead of running the puppeteer in the same machine. So basically hosted browser instance for puppeteer

**Comment by frinyvonnick** [comment]
It seems like a really specific issue. I invite you to use puppeteer directly. This package aims to remain pretty simple for basic usage. I close this issue since I won't make anything about it.

Thank you for taking time to share with me 🙏

**Comment by Tsopic** [comment]
Yeh, using puppeteer directly is not really a scaleable approach. But thanks.

I could just set the content of the page inside puppeteer and grab a screenshot of that after render, and works as well.

Actually, that's what I'm doing right now. Without a heavy 300mb library between.

**Comment by Tsopic** [comment]
Meanwhile with WebSocket pointing to and docker hosted instances I could scale to pretty much infinity. with loadbalancing.
