### ISSUE TITLE
@font-face font not working

### ISSUE THREAD

**Issue by ghost** [frinyvonnick/node-html-to-image#140]
The font not loading
my code

js:
let image = await nhti({
...
content: {
font1: data:font/truetype;base64,${new Buffer.from(fs.readFileSync("Magmawave-Caps.ttf")).toString("base64")}
},
...
});

html:
@font-face {
font-family: Magmawave;
src: url({{font1}}) format('truetype');
}

i tryed `truetype` & `woff` & `woff2` formats and still not working

& i tryed to do that
@font-face {
font-family: Magmawave;
src: url(data:font/truetype;base64,<myBuffer>) format('truetype');
}
and still not working

**Comment by frinyvonnick** [comment]
Without any new answer I close this issue. Feels free to reopen it 👍
