### ISSUE TITLE
Puppeteer Arguments

### ISSUE THREAD

**Issue by EviCoach** [frinyvonnick/node-html-to-image#143]
How can I pass in puppeteer arguments, it accepts an object, what are the keys?

**Comment by frinyvonnick** [comment]
Hi @EviCoach 👋 

You can pass in object in the **puppeteerArgs** properties. You can find the available properties in the puppeteer documentation [here](https://github.com/puppeteer/puppeteer/blob/v3.0.0/docs/api.md#puppeteerlaunchoptions).

**Comment by agustints** [comment]
puppeteerArgs: { args: ["--no-sandbox", "--disable-setuid-sandbox"] },

**Comment by EviCoach** [comment]
Thank you very much @frinyvonnick, @agustints
