### ISSUE TITLE
It is impossible to send launch arguments to the puppeteer instance.

### ISSUE THREAD

**Issue by tcortega** [frinyvonnick/node-html-to-image#144]
Hello, I was wondering why I can't pass any launch arguments to puppeteer, since the only option that sounds like allows you to do it, is `puppeteerArgs`, which type is `LaunchOptions`. There isn't anywhere which allows me to pass a string array, such as:

```
await nodeHtmlToImage({
    args: ["--no-sandbox"]
    });
```

**Comment by tcortega** [comment]
btw, for some reason, it seems like `LaunchOption` has no definition for `args` for me. I have 2 dependencies that uses puppeteer, I guess one of them is using an outdated version?

**Comment by tcortega** [comment]
Actually, it seems like this lib is the one using an outdated version. LaunchOptions no longer takes a string array of launch arguments.

**Comment by agustints** [comment]
same problem

**Comment by agustints** [comment]
puppeteerArgs: { args: ["--no-sandbox", "--disable-setuid-sandbox"] },

**Comment by tcortega** [comment]
> puppeteerArgs: { args: ["--no-sandbox", "--disable-setuid-sandbox"] },

This does not work if you have a nother module installed that requires a more up to date version of puppeteer. Since LaunchOptions no longer takes an `args: string[]` as an option to the interface.

As a temporary fix, I updated both `node-html-to-image` and `puppeteer-cluster` myself, and added an option to pass the args using a higher/more up to date version of puppeteer.

Not advertising but posting it as a temporary solution, to install, use: `yarn add @tcortega/node-html-to-image@latest`.

:D

**Comment by survfate** [comment]
@tcortega are you planning to make a PR of that change? I used your workaround package so far but it start to warning about outdate puppeteer version.

**Comment by tcortega** [comment]
> @tcortega are you planning to make a PR of that change? I used your workaround package so far but it start to warning about outdate puppeteer version.

Not really, the way I solved wasn't the best way to do it to be honest. Maybe if I have more time I can just go and refactor everything. But no plans for now.

**Comment by survfate** [comment]
> > @tcortega are you planning to make a PR of that change? I used your workaround package so far but it start to warning about outdate puppeteer version.
> 
> Not really, the way I solved wasn't the best way to do it to be honest. Maybe if I have more time I can just go and refactor everything. But no plans for now.

is it possible that you publish a version of the package with a more recent version of puppeteer for now?

**Comment by frinyvonnick** [comment]
puppeteer-cluster updated its version of puppeteer recently. I'll update it on node-html-to-image. It should save your problem :smile:

**Comment by frinyvonnick** [comment]
puppeteer-cluster updated its version of puppeteer recently. I'll update it on node-html-to-image. It should save your problem :smile:

**Comment by frinyvonnick** [comment]
Published in [v3.2.1](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.1) 🚀
