### ISSUE TITLE
Handlebars is always used even if "content" option is not provided

### ISSUE THREAD

**Issue by iveretelnyk** [frinyvonnick/node-html-to-image#147]
It not possible to use just html without handlebars. And this is problem to render html containing {{ }} as handlebars will try to parse and compile. 

index.ts line 28 
`const buffer = await makeScreenshot(page, { ...options, content, output, selector }) `

if you do not provide content option at this point this var become content = {}; thus handlebars will parse, but it should not.

**Comment by frinyvonnick** [comment]
Hi @iveretelnyk 👋 

Thank you for opening this issue. Nice catch 🙏

**Comment by frinyvonnick** [comment]
Published in [v3.2.1](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.1) 🚀
