### ISSUE TITLE
Feature request: add link support

### ISSUE THREAD

**Issue by NotCallMeHacker** [frinyvonnick/node-html-to-image#149]
Instead of having to input the HTML itself can we have support for links, so that it also renders images and is able to get external CSS/JS?

**Comment by frinyvonnick** [comment]
Hello @NotCallMeHacker 👋

I made this library to convert HTML into images. If you want to make screenshots of existing pages you can use directly puppeteer 🙂

**Comment by NotCallMeHacker** [comment]
Thatd be too easy ^^
