### ISSUE TITLE
Cannot find module './models/Screenshot'

### ISSUE THREAD

**Issue by bartuchavezc** [frinyvonnick/node-html-to-image#159]
Hi, today i give the next error in my proyect using version 3.2.2 and 3.2.1. 

> backend_1  | timestamp=2022-02-09-16:53:10-0300 app=app id=0 type=error message=Error: Cannot find module './models/Screenshot'
> backend_1  | timestamp=2022-02-09-16:53:10-0300 app=app id=0 type=error message=Require stack:
> backend_1  | timestamp=2022-02-09-16:53:10-0300 app=app id=0 type=error message=- /app/node_modules/node-html-to-image/dist/main.js

I solve it using 3.2.1 in my package.json
`"node-html-to-image": "3.2.0",`

**Comment by king0429** [comment]
Hi, today i have got the same issus, when i build my typescript project and startting to run the server it's said

, error: Cannot find module './models/Screenshot'

**Comment by frinyvonnick** [comment]
Hi @king0429 👋 

Ok, I'll try to reproduce it with a fresh Typescript project 👍

**Comment by survfate** [comment]
I just want to report that I ran into this today even on `v3.2.1`

**Comment by frinyvonnick** [comment]
It was released in [v3.2.3](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.3) 🚀  

Can someone confirm it is fixed (@survfate, @king0429 or @bartuchavezc) ?

**Comment by king0429** [comment]
> Hi @king0429 👋
> 
> Ok, I'll try to reproduce it with a fresh Typescript project 👍



> 

i'll  tey later. by the way, this package is very useful in my project, thanks so much!!  谢谢

**Comment by survfate** [comment]
> It was released in [v3.2.3](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.3) 🚀
> 
> Can someone confirm it is fixed (@survfate, @king0429 or @bartuchavezc) ?

working great for me now, appreciate the efforts
