### ISSUE TITLE
[Bug]: Typings for `puppeteerArgs` are using the incorrect type from Puppeteer

### ISSUE THREAD

**Issue by favna** [frinyvonnick/node-html-to-image#162]
This was suddenly brought to my attention when bumping the package from v3.2.0 to v3.2.3 in https://github.com/favware/archangel/pull/103. Felt it was very strange because even as recent as 6 days ago I saw you commented on an issue to use `args` and I couldn't possibly image Puppeteer removing such a critical option.

A bunch of digging later (godbless having access to cs.github.com so I could search both this repo and puppeteer's) and I found out that way back in February 2021 Puppeteer changed the TS types for `LaunchOptions`: https://github.com/puppeteer/puppeteer/pull/6888

All that said, I tracked down the bug and opened a PR to fix it but for tracking and formalities sake I also wanted to first open this issue. I figured it might also help anyone who runs into the same issue when they go searching.

**Comment by frinyvonnick** [comment]
Hello @favna 👋 

Thank you for opening this issue and taking time to explain it ❤️

**Comment by frinyvonnick** [comment]
This has been released in [v3.2.4](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.4) 🚀
