### ISSUE TITLE
Error: You must provide an output property.

### ISSUE THREAD

**Issue by tmauricio** [frinyvonnick/node-html-to-image#17]
En la documentacion hay un ejemplo del estilo:
return await nodeHtmlToImage({
    html: imageModelExample,
  });

que en lugar de guardar la imagen en el proyecto devuelve el binario. Pero no funciona porque el parametro "output" es obligatorio.

**Comment by frinyvonnick** [comment]
Hi @tmauricio,

Thank you for posting this issue.

I only speak english and french, sorry. With the title I guess this issue is duplicated with #12. A pull request #16 is open to fix this issue. I'll close this issue in favor of #12.
