### ISSUE TITLE
Error: Unable to launch browser...

### ISSUE THREAD

**Issue by zdev-online** [frinyvonnick/node-html-to-image#174]
`Unable to launch browser, error message: ENOENT: no such file or directory, mkdtemp 'C:\Users\ADMINI~1\AppData\Local\Temp\2\puppeteer_dev_chrome_profile-XXXXXX'.`

**Why is this happening and how to fix it?**

**Comment by frinyvonnick** [comment]
I just released [3.3.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.3.0) version which contain a feature to customise which puppeteer library node-html-to-image uses. It might help you making node-html-to-image work in a cloud context. Here is the documentation : https://github.com/frinyvonnick/node-html-to-image#using-different-puppeteer-libraries

Could you close the issue if it fixes it, please?

**Comment by frinyvonnick** [comment]
Without any new answer I close this issue. Feels free to reopen it 👍
