### ISSUE TITLE
[BUG] generate image timeout

### ISSUE THREAD

**Issue by williamsxu** [frinyvonnick/node-html-to-image#177]
"node-html-to-image": "^3.2.4"
node: 16.5.0
os: mac os 12.3.1

I am trying to generate images with loop:

```
for (let i =0; i<10; i++){
 await nodeHtmlToImage({
      puppeteerArgs: {
        timeout: 0,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        headless: false,
      },
      output: outpoutPath,
      html: html_static_data,
      content: {
           ...
      },
    });
}
```
But almost showing up the same error:
```
Error: Timeout hit: 30000
    at  xxxxx/node_modules/puppeteer-cluster/src/util.ts:73:19
    at Generator.next (<anonymous>)
    at fulfilled (/xxxxx/node_modules/puppeteer-cluster/dist/util.js:5:58)
```
So How I can set up the timeout to resolve this error?

Thanks!

**Comment by zc9** [comment]
I had the same problem

**Comment by zc9** [comment]
I have the same problem, looking for a solution

**Comment by zc9** [comment]
> "node-html-to-image": "^3.2.4" node: 16.5.0 os: mac os 12.3.1
> 
> I am trying to generate images with loop:
> 
> ```
> for (let i =0; i<10; i++){
>  await nodeHtmlToImage({
>       puppeteerArgs: {
>         timeout: 0,
>         args: ['--no-sandbox', '--disable-setuid-sandbox'],
>         headless: false,
>       },
>       output: outpoutPath,
>       html: html_static_data,
>       content: {
>            ...
>       },
>     });
> }
> ```
> 
> But almost showing up the same error:
> 
> ```
> Error: Timeout hit: 30000
>     at  xxxxx/node_modules/puppeteer-cluster/src/util.ts:73:19
>     at Generator.next (<anonymous>)
>     at fulfilled (/xxxxx/node_modules/puppeteer-cluster/dist/util.js:5:58)
> ```
> 
> So How I can set up the timeout to resolve this error?
> 
> Thanks!

did you solve it

**Comment by williamsxu** [comment]
> > "node-html-to-image": "^3.2.4" node: 16.5.0 os: mac os 12.3.1
> > I am trying to generate images with loop:
> > ```
> > for (let i =0; i<10; i++){
> >  await nodeHtmlToImage({
> >       puppeteerArgs: {
> >         timeout: 0,
> >         args: ['--no-sandbox', '--disable-setuid-sandbox'],
> >         headless: false,
> >       },
> >       output: outpoutPath,
> >       html: html_static_data,
> >       content: {
> >            ...
> >       },
> >     });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But almost showing up the same error:
> > ```
> > Error: Timeout hit: 30000
> >     at  xxxxx/node_modules/puppeteer-cluster/src/util.ts:73:19
> >     at Generator.next (<anonymous>)
> >     at fulfilled (/xxxxx/node_modules/puppeteer-cluster/dist/util.js:5:58)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So How I can set up the timeout to resolve this error?
> > Thanks!
> 
> did you solve it

not yet

**Comment by silhouette5366** [comment]
having the same issue, did anyone find any solution?

**Comment by igisho** [comment]
Same here

**Comment by frinyvonnick** [comment]
Hello 👋 

You can set the timeout as I explain it in this message : https://github.com/frinyvonnick/node-html-to-image/issues/179#issuecomment-1364546522

**Comment by silhouette5366** [comment]
@frinyvonnick any idea why you have added `process.exit(1)` in the catch statement at the end of the nodeHtmlToImage method?
this is causing my server to stop and POD to restart.

**Comment by ariv803** [comment]
For anyone working on this issue currently, please see my comment here:
https://github.com/frinyvonnick/node-html-to-image/issues/179#issuecomment-1655472677

**Comment by frinyvonnick** [comment]
It has been fixed in version [4.0.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v4.0.0) 🚀

**Comment by GuyBerkovichT** [comment]
@frinyvonnick there is still (on version 4.0.0) `process.exit(1)` in the main catch statement at the end of the nodeHtmlToImage which make it impossible to catch timeout errors from puppeteer and this is causing my server to stop and POD to restart.
there is any reason for this exit command?

**Comment by frinyvonnick** [comment]
@GuyBerkovichT this library was initially meant to be used in a command line context. Feel free to open an issue on this topic (this issue was about timeout which is different). If you have time you can either propose a solution to your problem 😄
