### ISSUE TITLE
Unable to launch browser, error message: Failed to launch the browser process!

### ISSUE THREAD

**Issue by prioarief** [frinyvonnick/node-html-to-image#178]
Unable to launch browser, error message: Failed to launch the browser process!
Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by sankara-sabapathy** [comment]
+++Same error

**Comment by sankara-sabapathy** [comment]
Error:
Error: Unable to launch browser, error message: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).

**Comment by RickRyan26** [comment]
same error

**Comment by ShalaQweghen** [comment]
Try passing this `puppeteerArgs: { args: ['--no-sandbox'] }` to `nodeHtmlToImage` function.

**Comment by macsimtv** [comment]
Not working :/

**Comment by frinyvonnick** [comment]
Hello there 👋 

I see a lot a comments here. I need some explanations and instructions (step by step) to reproduce easily your use cases. Otherwise I won't be able to help you.

**Comment by bpeters** [comment]
I believe they are probably running this in a aws-lambda env. It looks like your latest unrelease code fixes the issue with the custom puppeteer option.

**Comment by frinyvonnick** [comment]
I just released [3.3.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.3.0) version which contain a feature to customise which puppeteer library node-html-to-image uses. As @bpeters it might help you making node-html-to-image work in a cloud context. Here is the documentation : https://github.com/frinyvonnick/node-html-to-image#using-different-puppeteer-libraries

Could you close the issue if it fixes it, please?

**Comment by frinyvonnick** [comment]
Without any new answer I close this issue. Feels free to reopen it 👍

**Comment by baolongt** [comment]
If you use some cloud function
try to run 
node node_modules/puppeteer/install.js
before deployed
