### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by ZimberlyTheIrken** [frinyvonnick/node-html-to-image#18]
hi, i am writing a report. this is in repl.it, and i do have all dependencies, even the dependencies' dependencies installed. what do I do?
only use code snippet:
```
client.on('message', msg => {

  if (msg.content.startsWith('\`\`\`html') && msg.content.endsWith('\`\`\`')) {

    nodeHtmlToImage({

  	  output: 'image.png',

  	  html: msg.content.slice(7, msg.content.length - 3)

    })

	  .then(() => 

	    msg.channel.send(" ", {files: ["image.png"]})

	  )

  }

});
```

**Comment by SteeledSlagle13** [comment]
what is the console output?

**Comment by Keerat666** [comment]
I am getting the same " UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!" issue! Any help will be appreciated!

**Comment by frinyvonnick** [comment]
Hi @Keerat666 in repl.it too ?

**Comment by Keerat666** [comment]
Hey! Got it fixed by installing puppeteer.

Thanks!

**Comment by frinyvonnick** [comment]
It looks weird since `puppeteer` is listed in `node-html-to-image` [dependencies](https://github.com/frinyvonnick/node-html-to-image/blob/master/package.json#L11).

**Comment by Keerat666** [comment]
But for some reason, it was not installed. I tried creating an API by using the library and I am getting the image created in 19s. Any way to optimize it?

**Comment by frinyvonnick** [comment]
@Keerat666 This is not the purpose of this issue. I invite you to create a new one to discuss on this topic. Thank you 😄

**Comment by fiantinangon** [comment]
can we add ["--no-sandbox"] args ?

**Comment by frinyvonnick** [comment]
@ZimberlyTheIrken can you confirm the solution proposed by @fiantinangon fix your issue?

**Comment by frinyvonnick** [comment]
I'll close this issue since the author didn't participate to it for 20+ days. Feel free to reopen it if your issue is not solved.
