### ISSUE TITLE
ERROR Missing helper while calling nodeHtmlToImage()

### ISSUE THREAD

**Issue by st-trade** [frinyvonnick/node-html-to-image#180]
While trying to input handlebars helper functions, go an error stating that the function added in the handlebarsHelper property of the options object could not be found. I've dived into the repo and found that the handleBars property is apparently missing in the nodeHtmlToImage function definition.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/94030557/193427067-9a595c23-563d-4d6a-866d-1845e415329d.png">

**Comment by mcavazotti** [comment]
Same problem here

**Comment by frinyvonnick** [comment]
Without any new answer I close this issue. Feels free to reopen it 👍
