### ISSUE TITLE
Does it work on a linux maschine?

### ISSUE THREAD

**Issue by niklas-wulff** [frinyvonnick/node-html-to-image#188]
At the bottom is a screenshot of my error. Can someone help me? 
I try to use it in a node project running on a linux/debian maschine.
![grafik](https://user-images.githubusercontent.com/47000936/213761359-ce8467d2-42d3-4d82-adfb-708ddabfda07.png)

**Comment by frinyvonnick** [comment]
Did you check the documentation linked in the error message? There is a section about [UNIX](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix).

**Comment by niklas-wulff** [comment]
Thanks but same error 😢 

```
Error: Unable to launch browser, error message: Failed to launch the browser process! spawn /home/container/.cache/puppeteer/chrome/linux-1069273/chrome-linux/chrome ENOENT
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at Cluster.<anonymous> (/home/container/node_modules/puppeteer-cluster/dist/Cluster.js:119:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/container/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by niklas-wulff** [comment]
May the misstake is, that I does not installed chrome? 
If this is the misstake, how can I install it on linux?

**Comment by frinyvonnick** [comment]
@niklas-wulff in the troubleshooting section I linked you there is a list ofbdependencies you should install to make puppeteer work.

**Comment by niklas-wulff** [comment]
@frinyvonnick I installed the dependencies for debian but its still does not work..

**Comment by frinyvonnick** [comment]
I don't use linux but it is supposed to work on it. I invite you to try to use puppeteer directly. If it does not work either you can open an issue on puppeteer repository.

**Comment by frinyvonnick** [comment]
Without any new answer I close this issue. Feels free to reopen it 👍
