### ISSUE TITLE
Base64 image issue

### ISSUE THREAD

**Issue by SteeledSlagle13** [frinyvonnick/node-html-to-image#19]
Running into an issue trying to use a base64 local image.

I saw Buffer has a deprecation warning so im using the buffer readFileSync returns as my image.

Going off the example this is what I would think would work, but I get a transparent image and not the image i am passing in...

Not sure if it is an issue or a thing on my end...

__Code__
```JS
const nodeHtmlToImage = require('node-html-to-image')
const fs = require('fs');

const image = fs.readFileSync('./test-2.png', 'base64');

nodeHtmlToImage({
    output: './image.png',
    html: `
    <html>
        <body>
            <img src="{{imageSource}}" />
        </body>
    </html>
            `,
    content: {
        imageSource: image
    },
    transparent: true
})
.then(() => console.log('The image was created successfully!'))
```

__Workspace Setup__
![image](https://user-images.githubusercontent.com/25378777/80918794-4e4d7d00-8d2c-11ea-9344-d6f9ade2c06f.png)

__Current Example from README__
```JS
const nodeHtmlToImage = require('node-html-to-image')
const fs = require('fs');
 
const image = fs.readFileSync('./image.jpg');
const base64Image = new Buffer(bitmap).toString('base64');
 
nodeHtmlToImage({
  output: './image.png',
  html: '<html><body><img src="{{imageSource}}" /></body></html>',
  content: { imageSource: base64Image }
})
```

__Current Output__
![image](https://user-images.githubusercontent.com/25378777/80918957-27dc1180-8d2d-11ea-9149-0b458040a4be.png)

__Expected Output__
![image](https://user-images.githubusercontent.com/25378777/80918991-375b5a80-8d2d-11ea-85d7-c3264b9c3c63.png)

**Comment by SteeledSlagle13** [comment]
it's working with remote images but my use case is for local images

**Comment by frinyvonnick** [comment]
Hi @SteeledSlagle13 your example does not use the code version in the README to deal with [local images](https://github.com/frinyvonnick/node-html-to-image#dealing-with-images). Could you try using it?

**Comment by SteeledSlagle13** [comment]
hey @frinyvonnick looks like the readme here worked
i was going off the readme on [npm page](https://www.npmjs.com/package/node-html-to-image)
![image](https://user-images.githubusercontent.com/25378777/81201990-93231f00-8f8b-11ea-85a4-8006b86d5a20.png)
Thank you very much! 😄

**Comment by frinyvonnick** [comment]
I close this issue 👍 I will be fixed with the new release 😄
