### ISSUE TITLE
problem running on linux (docker)

### ISSUE THREAD

**Issue by valdomirovanzo** [frinyvonnick/node-html-to-image#192]
hello everyone, I'm facing this problem in running the component in docker, in a test base in windows it works perfectly. Can you help me in this process?

![image](https://user-images.githubusercontent.com/65238863/217512755-0ea34461-c591-42d1-ab2f-0a7413cbef08.png)

**Comment by frinyvonnick** [comment]
Hello @valdomirovanzo 👋 Thank you for opening this issue 🙏 Did you checked the troubleshooting documentation from puppeteer linked at the end of the error? It has a [section](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) about using puppeteer with Docker. node-html-to-image uses puppeteer under the hood 😄

**Comment by frinyvonnick** [comment]
Thank you @rawatravi 🙏 Since a solution has been provided I close the issue 👍
