### ISSUE TITLE
Any way to increase the conversion speed?

### ISSUE THREAD

**Issue by Keerat666** [frinyvonnick/node-html-to-image#20]
Got an initial time of 19s to convert an html to image. Any way to fasten up the process? 

Thanks!

**Comment by jewkesy** [comment]
Hey @Keerat666, have you got an example page?

The conversion is done via Puppeteer, the library is just a wrapper.  However 19secs does sound high.

**Comment by fiantinangon** [comment]
You can minify your HTML script before rendering it, and compress all image assets, it will help to increase rendering performance, cause puppeteer can open your HTML page faster
