### ISSUE TITLE
puppeteer is no longer supported

### ISSUE THREAD

**Issue by obzc** [frinyvonnick/node-html-to-image#200]
Hello,

I think puppeteer has been deprecated. Is there any solution for this?

`npm WARN deprecated puppeteer@15.5.0: < 19.4.0 is no longer supported`

**Comment by frinyvonnick** [comment]
Hi @obzc 👋 

I upgraded puppeteer to latest version in this pull request : https://github.com/frinyvonnick/node-html-to-image/pull/209

It has been released in version [4.0.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v4.0.0) 🚀
