### ISSUE TITLE
Anyway to mix handlebars with fs.readFile?

### ISSUE THREAD

**Issue by impactcolor** [frinyvonnick/node-html-to-image#201]
Example code that doesn't provide the results:

`    const html_code = fs.readFileSync(`/var/www/vhosts/preview.inkto.art/httpdocs/html/${filename}`, 'utf8');

    try {
        nodeHtmlToImage({
            puppeteerArgs: {
                headless: true,
                args: ['--no-sandbox', '--disable-setuid-sandbox']
                },
            output: `/var/www/vhosts/preview.inkto.art/httpdocs/public/${responseImg}`,
            html: html_code,
            content: { Text: 'testMe'}
          })
          .then(() => res.send('image created check server'))
          .catch(e => res.send(`We have an error: ${e}`))

    } catch (error) {
        res.send('we have an error');
    }`

The response error: 
X�:V$�BA.|�:'esponse received from application

The html contains a text field: `{{ Text }}`

**Comment by frinyvonnick** [comment]
Hi @impactcolor 👋 

handlebars expressions must not contains spaces. You must change {{ Text }} to {{Text}} in order to make it work 😄
