### ISSUE TITLE
WARNING - Will exhaust Linux threads

### ISSUE THREAD

**Issue by AriVagelatos-KSO** [frinyvonnick/node-html-to-image#213]
This library creates puppeteer clusters for each request which will quickly exhaust native linux threads under load. The same puppeteer cluster should be reused as a singleton as a fix.

**Comment by frinyvonnick** [comment]
If someone is interested in contributing, feel free to  work on this 👍

**Comment by frinyvonnick** [comment]
I think it is linked to #80 I'll close this one in favor of the other.
