### ISSUE TITLE
Serverless Run: custom Puppeteer

### ISSUE THREAD

**Issue by davodm** [frinyvonnick/node-html-to-image#214]
Hi, I used the function on a lambda function with puppeteer-core and [@sparticuz/chromium](https://github.com/Sparticuz/chromium#sparticuzchromium) based on your document.

But the error I'm facing is:

> Unable to launch browser, error message: spawn ETXTBSY
    at Cluster.<anonymous> (/var/task/node_modules/puppeteer-cluster/dist/Cluster.js:119:23)

Which comes from [node-html-to-image](https://github.com/frinyvonnick/node-html-to-image) package dependencies.

Here are the versions I'm using:
"puppeteer-core": 21.3.7
"@sparticuz/chromium": 117.0

Here is the way I'm using the function:
```javascript
// AWS Config
    let AWSconf = {};
    if (!isOffline() && chromium) {
      AWSconf = {
        puppeteer: puppeteerCore,
        puppeteerArgs: {
          args: chromium.args,
          executablePath: await chromium.executablePath(),
          headless: chromium.headless,
          ignoreHTTPSErrors: true,
          defaultViewport: chromium.defaultViewport,
          args: [
            ...chromium.args,
            "--hide-scrollbars",
            "--disable-web-security",
            '--no-sandbox'
          ],
        },
      };
    }
    // Generate the image
    await nodeHtmlToImage({
      html: renderedHtml,
      content: data, // It already using Handlebars
      output: $outputPath + outputFileName,
      transparent: true,
      ...AWSconf,
    });
```

**Comment by ranstyr** [comment]
@davodm Did you solve it?

**Comment by davodm** [comment]
> @davodm Did you solve it?

Tried to update Chromium and puppeteer (matched with each other) and it worked.

**Comment by frinyvonnick** [comment]
I close this issue since you solved it on your own 😄
