### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by jordan314** [frinyvonnick/node-html-to-image#3]
Thanks for this! Would it be possible to support transparent backgrounds?

**Comment by frinyvonnick** [comment]
Hi @jordan314, thank you for this suggestion. It seems possible using the `omitBackground` property of `screenshot` method. Here is the call to [screenshot](https://github.com/frinyvonnick/node-html-to-image/blob/master/src/index.js#L26). What would you prefer a generic property called `puppeteerScreenshotArgs` to enable overriding screenshot default values or a specific property like `transparent`. Maybe both?

**Comment by jordan314** [comment]
Ooh omitBackground: true worked, thank you! For my purposes a specific property like transparent would work. Thanks!

**Comment by frinyvonnick** [comment]
It is available in version 1.2.0 🎉
