### ISSUE TITLE
How to set width and height value.

### ISSUE THREAD

**Issue by Julianvschijndel** [frinyvonnick/node-html-to-image#32]
Hello,

First of all. You're a legend. This works 100%. There is still one question I have in mind.
How to set a width/height value to the image. I can't get it.

Hope to hear soon.

**Comment by Julianvschijndel** [comment]
Also, is t possible to store the **html** into a file and get it when the code is called?

**Comment by frinyvonnick** [comment]
Hi @Julianvschijndel 👋 

There is a section about [output image resolution](https://github.com/frinyvonnick/node-html-to-image#setting-output-image-resolution) in the README. It should answer your first question 😄

Sure, you can store the HTML in a file for example called `template.html` then import it using `fs` module:

```js
const fs = require('fs')

const template = fs.readFileSync('./template.html').toString('utf8')
```

**Comment by Julianvschijndel** [comment]
Hi @frinyvonnick ,

Thanks for the code I will check that asap. Also, can I use image that are coded in CSS but then use it like a png/jpg/jpeg and not de base64?

Hope to hear soon!

**Comment by frinyvonnick** [comment]
If the images aren't stored locally it will work fine.

**Comment by Julianvschijndel** [comment]
Hi @frinyvonnick ,

So the image cannot be stored locally to get it directly from css but needs to be on a website?

**Comment by frinyvonnick** [comment]
Exactly, If it is stored locally you need to use the base64 method that is describe in the README.

**Comment by Julianvschijndel** [comment]
Hi @frinyvonnick 

Everything you said works fine. Thanks for the quick support! Have a nice day!
