### ISSUE TITLE
Error launching browser process on Raspberry Pi

### ISSUE THREAD

**Issue by LegoFigure11** [frinyvonnick/node-html-to-image#35]
Heya! I'm trying to use this module in a discord bot running on my raspberry pi (Raspbian 4.19.66-v7+, node v13.14.0) and I run into the following error when trying to use the module: https://pastie.io/vyzgce.txt

[Here's the code I'm running](https://github.com/LegoFigure11/moodE/blob/master/discord/commands/color.js), and it works as expected when run on my windows desktop. As you can see, I tried the fix from #18, ensured that all of the dependencies (and their dependencies) are installed, and also followed the instructions from [here](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) as suggested by the stack. Occasionally i will get a different error suggesting a re-runof  `npm install` which I have done numerous times, which doesn't fix the problem.

Any ideas? Thanks in advance.

**Comment by frinyvonnick** [comment]
Hi @LegoFigure11, thank you for sharing you issue 🙏 

It definitely seems related to puppeteer. You looked over all related ressources which is nice. I recommend making an reproduction example without node-html-to-image and post an issue on puppeteer repository.

**Comment by LegoFigure11** [comment]
Thanks for the swift response! 

I (finally) managed to get it working with puppeteer on its own using the following code:
```js
(async () => {
  const browser = await puppeteer.launch({headless: true, executablePath: 'chromium-browser', args: ["--no-sandbox", "--disable-setuid-sandbox"]});
  const page = await browser.newPage();
  
  await page.setContent(html);
  
  const element = await page.$("body");
 
  await element.screenshot({path: 'example.png'});
 
  await browser.close();
})();
```
So modifying the code in my previous post to
```js
const image = await nodeHtmlToImage({
			puppeteerArgs: {executablePath: "chromium-browser", args: ["--no-sandbox", "--disable-setuid-sandbox"]},
			// Do everything else
}
```
makes it work!

Thanks so much for this module, and once again for your response. Closing this as resolved.

**Comment by frinyvonnick** [comment]
Glad you achieved to fix it 👌
