### ISSUE TITLE
<! DOCTYPE html> Error

### ISSUE THREAD

**Issue by imenesesl** [frinyvonnick/node-html-to-image#36]
Hello, it's funny, this error, luckily I fixed it but it would be nice to see what happens.

I am using **`" pug ":" ^ 3.0.0 "`** to create an HTML template parsed to string, apart from that I use **`" pdf-puppeteer ":" ^ 1.1.10 "`**, all good so far, it is generated the pdf.
  Now go into action **`" node-html-to-image ":" ^ 2.1.1 "`**, I passed the same template but error
**`Node has 0 height.`**

The problem is not critical, but it is complex to find and it is only for this reason:
**<! DOCTYPE html>**
![image](https://user-images.githubusercontent.com/33881595/84528576-93f35300-aca5-11ea-9b5a-622b3ec33a57.png)

If the template contains exactly that, it breaks, my solution is no big deal, just delete that part

![image](https://user-images.githubusercontent.com/33881595/84528700-c735e200-aca5-11ea-8a5a-f571e740c73d.png)

And now if, with that, both the pdf and the image are solved and are created.

With this another problem was born that I will leave in the issue #37

**Comment by frinyvonnick** [comment]
Hi @imenesesl 👋 

Thank you for sharing your issue. 

Do you have some error or stack trace to share when it breaks?

Furthermore node-html-to-image comes with a template engine called handlebars. Here is an [example](https://github.com/frinyvonnick/node-html-to-image#example-with-handlebars) of how to use it.

**Comment by imenesesl** [comment]
@frinyvonnick  It is interesting to experiment a little to know how it works with more complex data or objects with various properties.

**Comment by imenesesl** [comment]
@frinyvonnick The only thing it generates is **Node has 0 height**, which is not very intuitive, accompanied by a 500 code

**Comment by frinyvonnick** [comment]
This issue comes from puppeteer. It is thrown by the screenshot method.
