### ISSUE TITLE
Define height and width in html

### ISSUE THREAD

**Issue by imenesesl** [frinyvonnick/node-html-to-image#37]
Nothing has changed since issue #36 , the same libraries are still used, now the problem is that, if the image that is generated is cropped.

Both libraries receive the same template generated by pug (taking the consideration described in issue # 36 to generate the image)

PDF:
![image](https://user-images.githubusercontent.com/33881595/84529084-72df3200-aca6-11ea-8946-23b8d73f18e6.png)

IMAGE:
![image](https://user-images.githubusercontent.com/33881595/84529102-78d51300-aca6-11ea-9a46-202fa5c42d19.png)

In pdf-puppeteer it is solved in this way

![image](https://user-images.githubusercontent.com/33881595/84529239-b76acd80-aca6-11ea-9933-23e5f42e80c3.png)

But, what would be the way to do it in **`node-html-to-image`**?

**Comment by frinyvonnick** [comment]
Hi @imenesesl, It is explained in the section [Setting output image resolution](https://github.com/frinyvonnick/node-html-to-image#setting-output-image-resolution). Hope it will help 👍

**Comment by imenesesl** [comment]
@frinyvonnick  Thank you! it was more a style theme in the file consuming pug
