### ISSUE TITLE
Output image won't display images.

### ISSUE THREAD

**Issue by samuelbeard** [frinyvonnick/node-html-to-image#4]
If I have an image in my html template, it is not displayed in the outputted image.

Is this something I am missing or does this not work?

**Comment by frinyvonnick** [comment]
Hi @samuelbeard, 

Thank you for taking the time to post this issue 🙏 

Does this image is present locally or it is an url ? In case of local images I recommend you having image in base 64. Here is an [example](https://stackoverflow.com/questions/24523532/how-do-i-convert-an-image-to-a-base64-encoded-data-url-in-sails-js-or-generally) to convert image to base64. Then you can pass it to the template with the content property. Do you see what I mean?

**Comment by samuelbeard** [comment]
Great idea. Thanks!

**Comment by frinyvonnick** [comment]
I close the issue. I let you reopen it if needed 👍
