### ISSUE TITLE
Changing body size with background corrupts the end result

### ISSUE THREAD

**Issue by OsamaJBR** [frinyvonnick/node-html-to-image#46]
I'm trying to build a postcard image (png) using HTML, the body size is 320x512 and the background is the same. If you open this on chrome with device size (320x5120 it works perfectly. 

See below : 
![Alt desc](https://i.imgur.com/is35Vhb.png)

But when I use node-html-to-image to convert the same HTML, the image goes to Right, and the postcard is corrupted. See: ![Alt desc](https://i.imgur.com/TpQaHS6.png)

Here is the HTML to reproduce.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Post Card</title>
</head>
<style>
    body {
          width: 320px;
          height: 512px;
    }
</style>
<style>
    .row {
        margin-right: 0;
    }
    .background {
        background-image: url(https://yeebaa-uploads-staging.s3.eu-west-1.amazonaws.com/templates/backgrounds/97089/419a5/093e9/4f8e7/5144c/1492f/bdc27/ac952/5745b/91ba7/60f69/019b9/d588.png);
        background-position: inherit;
        background-repeat: no-repeat;
        background-size: 320px 512px;
        height: 512px;
        width: 320px;
    }

    .input,
    .input {
        position: absolute;
        background-color: rgb(0, 0, 0, 0);
        border: none;
        border-bottom: 1px solid white;
        width: 220px;
        color: #000000;
        text-align: center;
    }

    
    .to-input {
        left: 50px;
        top: 30px;
        font-size: 20px;
    }
    
    .from-input {
        left: 50px;
        top: 420px;
        font-size: 20px;
    }
</style>
<body>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-1"></div>
        <div class="col-lg-4 col-md-4 col-11">
            <div class="background">
                <form>
                                <input class="input to-input" name="to" id="to" type="text" value="osama">
                                <input class="input from-input" name="from" id="from" type="text" value="nisreen">
                </form>
            </div>
        </div>
        <div class="col-lg-4 col-md-4"></div>
    </div>
</body>

</html>
```

**Comment by frinyvonnick** [comment]
Hi @OsamaJBR, thank you for reporting this issue. In non-responsive mode I reproduce your issue (as you can see there is an empty space on the left):

![image](https://user-images.githubusercontent.com/13099512/87141937-1458a400-c2a4-11ea-8005-242a0a5c9e34.png)

It is related to page viewport. There are two solutions to fix your issue:

- Remove the first div `<div class="col-lg-4 col-md-4 col-1"></div>` which is responsible of the empty space on the left in "desktop" mode.
- Set the browser default viewport `nodeHtmlToImage({ puppeteerArgs: { width: 320, height: 512 }, ...otherOptions })` (So the media queries from bootstrap are activated)

Hope it will help. Please close this issue if it fixes it 😄

**Comment by OsamaJBR** [comment]
It seems that the HTML I'm using is not right. 

I've added browser options and fixed the HTML and now it works fine. Thanks.
