### ISSUE TITLE
When deployed to heroku, "Unable to launch browser, error message: Failed to launch the browser process!" error occurs.

### ISSUE THREAD

**Issue by sajib21** [frinyvonnick/node-html-to-image#49]
Unable to launch browser, error message: Failed to launch the browser process!
Found this in the logs: 
`/app/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

I tried passing `puppeteerArgs: { args: ["--no-sandbox", "--disable-setuid-sandbox"] }` like

    nodeHtmlToImage({
        html: "...",
        content: {...},
        puppeteerArgs: { args: ["--no-sandbox", "--disable-setuid-sandbox"] }
    );
But it didn't work.

**Comment by frinyvonnick** [comment]
Hi @sajib21 👋 

Thank you for opening this issue. Did you follow the [instructions](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku) in puppeteer documentation about using it with Heroku?

**Comment by sajib21** [comment]
Thanks for the response. I did install a buildpack with `heroku buildpacks:set <buildpack repo>` but after doing so, the whole app was crashing. I foind the command and buildback git repo in a stackoverflow post. But now after trying your mentioned link, it worked finally. 

So my solution was following these instructions: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku

go to heroku project > settings > add buildpack > paste  https://github.com/jontewks/puppeteer-heroku-buildpack > save

server side:

    nodeHtmlToImage({
        html: "...",
        content: {...},
        puppeteerArgs: { args: ["--no-sandbox"] }
    );

And it works like a charm. :D

**Comment by aahnik** [comment]
If anybody is running on **Heroku** and facing the same error:

Add the **buildpack** : The url for the buildpack is below :

`https://github.com/jontewks/puppeteer-heroku-buildpack`

Ensure that you're using **`--no-sandbox`** mode

```python
launch({ args: ['--no-sandbox'] })
```
