### ISSUE TITLE
Showing images or having background

### ISSUE THREAD

**Issue by jasetom** [frinyvonnick/node-html-to-image#5]
Hi there, is there a way to display images using <img> tag or using CSS? I can't seem to be able to display those when I render the images using this module

**Comment by frinyvonnick** [comment]
Hi @jasetom 👋 

Thank you for posting this issue. Are the images you want to display on your local disk? If so I invite you to read this [issue](https://github.com/frinyvonnick/node-html-to-image/issues/4) in which I explain how to display local images.

If this solves your issue feel free to close it.

**Comment by jasetom** [comment]
Perfect, it worked. thank you!
