### ISSUE TITLE
page.close() missing

### ISSUE THREAD

**Issue by jaoxico** [frinyvonnick/node-html-to-image#51]
I am using it in my project which I also use puppeteer.

The lack of "await page.close()" in "src/index.js" causes my script to fail when running "browser.newPage()".

**Comment by frinyvonnick** [comment]
Hi @jaoxico 👋 

Thank you for opening this issue. Could you share your code so I could reproduce it please 🙏

**Comment by frinyvonnick** [comment]
I close this issue, feel free to reopen it if you have further information.
