### ISSUE TITLE
Not showing emoji

### ISSUE THREAD

**Issue by armandoarmando** [frinyvonnick/node-html-to-image#52]
Hey everyone!
I'm trying to create an image with emojis on my Ubuntu server.

`return await nodeHtmlToImage({
    output: `./public/output`,
    html: htmlFile,
    puppeteerArgs: { args: ["--no-sandbox"] }
  }).then(() => {
    return { image_src: output }
  })
    .catch((err) => {
      console.log('nodeHtmlToImage Error: ', err)
      return err
    })`

Result:
![image](https://user-images.githubusercontent.com/46790753/88550330-210e2380-d02a-11ea-9e0f-1dd912235934.png)

It's not showing the emoji. Why? 

Thanks

**Comment by frinyvonnick** [comment]
Hi @armandoarmando 👋 

Thank you for opening this issue. This seems related to your environment. Depending on your Ubuntu installation process emoji support is missing. Check out this [article](https://www.starryhope.com/linux/enable-emojis-ubuntu-1904/) to learn more. Does it solve your issue?

**Comment by armandoarmando** [comment]
Amazing! Works great! thank you very much @frinyvonnick

**Comment by frinyvonnick** [comment]
Nice, I'm glad it helps 😄 I close this issue 👍
