### ISSUE TITLE
How to run this as headless on my server ?

### ISSUE THREAD

**Issue by sharadcodes** [frinyvonnick/node-html-to-image#53]
I have to my app on heroku and it throws error if I dont use headless or disable the sandbox version of puppeteer.

**Comment by frinyvonnick** [comment]
Sure, it is explained in [puppeteer documentation](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku) 👍

**Comment by sharadcodes** [comment]
Thanks for the reply I got it fixed.
Now the emojis are not rendered any way to fix that ?

**Comment by frinyvonnick** [comment]
I explained it in the issue #52. Hope it will help 👌

**Comment by sharadcodes** [comment]
Thanks for the quick reply :+1:

**Comment by sharadcodes** [comment]
@frinyvonnick It dosent work :(

**Comment by frinyvonnick** [comment]
Maybe this [package](https://github.com/SimonBriche/heroku-buildpack-emoji-support) will help you. I don't know Heroku, I can't help you more on this topic, sorry 😞

**Comment by sharadcodes** [comment]
> Maybe this [package](https://github.com/SimonBriche/heroku-buildpack-emoji-support) will help you. I don't know Heroku, I can't help you more on this topic, sorry

No problem, I'm remotely sending the text, some emojis are rendered as black and white some are not rendered. 

Thanks for the time :smile:

**Comment by sharadcodes** [comment]
> Maybe this [package](https://github.com/SimonBriche/heroku-buildpack-emoji-support) will help you. I don't know Heroku, I can't help you more on this topic, sorry 😞  

It worked😄

**Comment by IgorTitov** [comment]
> Sure, it is explained in [puppeteer documentation](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku) 👍

Sorry, could you please explain a bit more? When using node-html-to-image, puppeteer is used as dependency, so it would be great if you'd shown what and where exactly something mush be changed. In the above link there is explanation how to deal with puppeteer when it's used directly but in this case it's used indirectly via node-html-to-image...

**Comment by frinyvonnick** [comment]
@IgorTitov there is a [puppeteerArgs option](https://github.com/frinyvonnick/node-html-to-image#options) in which you can pass any pupperteer argument you want.

```js
const nodeHtmlToImage = require('node-html-to-image')

nodeHtmlToImage({
  output: './image.png',
  html: '<html><body>Hello world!</body></html>',
  puppeteerArgs: { args: ['--no-sandbox'] }
})
  .then(() => console.log('The image was created successfully!'))
```

**Comment by IgorTitov** [comment]
Thank you for a quick reply! It worked:)
