### ISSUE TITLE
Generation of Images takes a really long time.

### ISSUE THREAD

**Issue by bna-ch** [frinyvonnick/node-html-to-image#56]
I am trying to generate an image from html, but it takes around 10 seconds to generate one image. I only have a single table in the html. Is there any way to reduce the image generation time?

**Comment by frinyvonnick** [comment]
Hi @bna-ch 👋 

Could you share the code that generates the image so I could reproduce it?

**Comment by TheDevJulian** [comment]
Hi,

Also having the same problem. I will post my problem with code here to not create duplicate.
Images takes like minimal 3 tot max 15 seconds to generate. See my code:

```js
const cardID = Math.floor(Math.random() * 1000000000000000);
nodeHtmlToImage({
        output: `./cards/${cardID}.png`,
        html: fs.readFileSync(`./data/cards/welcome.html`).toString('utf8'),
        content: {
            avatar: userAvatar,
            ... more of this content vars.
        }
    });
    const embed = new Discord.MessageEmbed()
        .setColor(config.COLORS.YELLOW)
        .setAuthor(`Welcome to ${message.guild.name}`, message.guild.iconURL({ dynamic: true }))
        .attachFiles([attachment])
        .setImage(`attachment://${cardID}.png`)
    channel.send(embed);
```

I tried with a `.then()` but still generating slow. Also a `async` with `await` will not speed up the process. Every cards needs another name. I don't know if the problem is coming from that.

If there is more information u need, please let me know!

**Comment by bna-ch** [comment]
Hi @frinyvonnick I am actually just using the sample code snippet provided in the docs.

`const nodeHtmlToImage = require('node-html-to-image')

nodeHtmlToImage({
  output: './image.png',
  html: `--replaced with my HTML content--- `
})
  .then(() => console.log('The image was created successfully!'))`

I just replaced the html string with my own html table, it would just take between 5 - 10 seconds to generate an image.

**Comment by frinyvonnick** [comment]
With the example it lasts 330ms:
![image](https://user-images.githubusercontent.com/13099512/93744039-69445f00-fbf1-11ea-820e-993ca68e1684.png)

Without the html content I can figure out what takes so long. One of you can share it to me?

**Comment by TheDevJulian** [comment]
Hi @frinyvonnick ,

I use this for my Discord bot and I runned some test myself. With a command I generated 200 images in one time.

I tracked the time the images how long it will take from them to be created. I saw that the fastest was **150 ms** and the slowest was **200 ms** with this my problem is fixed for now. I added a logger that will track how long images will be generated.

Thanks again for building this awesome package.

Kind regards!

**Comment by eduardoabpereira** [comment]
i'm facing the same @bna-ch case

**Comment by frinyvonnick** [comment]
Hello @eduardoabpereira, 

Could you share the code/html so I can reproduce the issue?

**Comment by eduardoabpereira** [comment]
I added a sample repo at [image-test](https://github.com/eduardoabpereira/image-test) with the same content i have at my main repo to reproduce.

**Comment by frinyvonnick** [comment]
Thank you @eduardoabpereira 🙏

**Comment by frinyvonnick** [comment]
@eduardoabpereira I added code to print execution time of `node-html-to-image`:

```diff
+  const start = new Date()
  const image = await nodeHtmlToImage({
    html,
    content: {
      date: '21/08/2020',
      transactionCode: 'abcdef564564abcdef',
      payerName: 'company name',
      payerDocument: 'xx.xxx.xxx/xxxx-xx',
      amount: 'R$ 1000.00',
      description: 'teste',
      beneficiaryName: 'eduardo',
      beneficiaryDocument: 'xxx.xxx.xxx-xx',
      beneficiaryBank: 'testee',
      beneficiaryAgency: 'xxxx',
      beneficiaryAccount: 'xxxxx-x',
      beneficiaryAccountType: 'Conta Corrente',
    },
    puppeteerArgs: {
      defaultViewport: {
        width: 1080,
        height: 800,
      },
    },
  });
+  const end = new Date() - start
+  console.info('Execution time: %dms', end)
```

It lasts 1.5s for me. `node-html-to-image` uses puppeteer so there is an overhead of time while Chromium is starting.

![image](https://user-images.githubusercontent.com/13099512/93773361-54cb8b00-fc20-11ea-9b0f-1fcf54fce466.png)

If you use this technique to print execution time on your main repository it lasts longer?

**Comment by bna-ch** [comment]
hey, I solved my issues by writing custom css. Initially I was using bootstrap styles, linked through cdn. But, once I changed it to custom css, it worked like a charm, and I was able to reduce the execution time by half.
