### ISSUE TITLE
Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; AWS lambda

### ISSUE THREAD

**Issue by rajanaggarwal1** [frinyvonnick/node-html-to-image#57]
trying to use this package with aws lambfa but getting size issue.can some one help on this?

Error :  Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 7fa17ead-21c3-410e-9269-c187c12c9b84; Proxy: null).

Thanks in advance

**Comment by frinyvonnick** [comment]
Hi @rajanaggarwal1,

It seems to be an error specific to AWS. node-html-to-image is really small but it uses puppeteer so it might be to weighty to work on AWS. I can't help you on this, I close this issue.
