### ISSUE TITLE
How to set window size?

### ISSUE THREAD

**Issue by MarkDeuerling** [frinyvonnick/node-html-to-image#60]
How to set the size of the sceenshot? Already passed the --window-size=1920,1080 flag, but it still used the default resolution.

**Comment by frinyvonnick** [comment]
Hi @MarkDeuerling 👋 

There is a [section](https://github.com/frinyvonnick/node-html-to-image#setting-output-image-resolution) in the README on this topic!

Please close this issue if it helps you 👌
