### ISSUE TITLE
Can html file be used?

### ISSUE THREAD

**Issue by impactcolor** [frinyvonnick/node-html-to-image#67]
Hello bro, thanks for this module.
Can html file be used instead of an html string?

In example:
```
  nodeHtmlToImage({
    output: './image.png',
    html: './myhtmlfile.html'
  })
```
Thank you!

**Comment by frinyvonnick** [comment]
Hi @impactcolor 👋 

Thank you for posting this issue. Here is the way to use an html file:

```js
const fs = require('fs')
const path = require('path')
const nodeHtmlToImage = require('node-html-to-image')

const buffer = fs.readFileSync(path.join(__dirname, 'index.html'))
const html = buffer.toString('utf8')

nodeHtmlToImage({
  output: './image.png',
  html, 
})
  .then(() => console.log('The image was created successfully!'))
```

If it fixes your issue, please close it 😄

**Comment by frinyvonnick** [comment]
Maybe this example could be added to the README 🤔 ?

**Comment by impactcolor** [comment]
Awesome thank you.  Yes adding it to the example would be great.

**Comment by 0rangeFox** [comment]
Hey, if HTML can be included, how can I activate the scripts in files and created by myself but all initialized within this HTML, how can I render?

**Comment by frinyvonnick** [comment]
Hi @0rangeFox 👋 Do you have some example in which you experience issues you can share?

**Comment by 0rangeFox** [comment]
Hey @frinyvonnick, it's been a long time and I never received any notification and didn't even notice this, but at that time I was doing an experiment and I had an idea, I don't remember exactly what it was about, but anyway, I wanted to apologize for leaving this open and not saying anything. But thanks anyway and it's solved from my part.
