### ISSUE TITLE
Render an element in the body

### ISSUE THREAD

**Issue by SilveryStar** [frinyvonnick/node-html-to-image#71]
Sometimes I just want to convert one element in the html file into a picture, instead of the body elements.Can this feature be implemented?Thanks!

**Comment by frinyvonnick** [comment]
Hi @SilveryStar 👋 

Thank you for posting this issue 👍 Would you be interested in opening a pull request with an implementation for this feature?

**Comment by SilveryStar** [comment]
Sorry, I am still a newbie of github and node, but I think we can add an option `element` (default value is body).Then modify the `puppeter page.$(selector)`  to implemente the feature 
https://github.com/frinyvonnick/node-html-to-image/blob/dd258ddecf873c874c686e641050190b3b4f7cba/src/screenshot.js#L25

**Comment by frinyvonnick** [comment]
Yes this is it 👍 Would you try it? I can help you 😄

**Comment by frinyvonnick** [comment]
This was released in [v3.2.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.0) 🚀
