### ISSUE TITLE
Fonts Not Loading

### ISSUE THREAD

**Issue by MarkDeuerling** [frinyvonnick/node-html-to-image#72]
Hi,
I try to add a font, but the font won't render at all.
I've added the font in the header and use it as a font-family in my body.

`<head>
    <style>
      @font-face {
        font-family: testFont;
        src: url(https://some/awesome/font.ttf);
      }
    </style>
  </head>`

I already tried to wait for it, but still no success.

**Comment by frinyvonnick** [comment]
Hi @MarkDeuerling,

Thank you for posting this issue 👍 

Here is an [example](https://github.com/frinyvonnick/node-html-to-image/issues/33#issuecomment-635151349) on how to use webfonts with node-html-to-image. Please close this issue it fixes it 👍

**Comment by frinyvonnick** [comment]
@MarkDeuerling would you be interested in adding an example to the README on how to use a webfont?

**Comment by MarkDeuerling** [comment]
@frinyvonnick I created a pull resquest with an example.
