### ISSUE TITLE
requirements?

### ISSUE THREAD

**Issue by stefanocudini** [frinyvonnick/node-html-to-image#73]
it lib require chrome installed in the ssystem?

what rendering engine use it?

**Comment by frinyvonnick** [comment]
Hi @stefanocudini 👋 

As you can see in the [dependencies](https://github.com/frinyvonnick/node-html-to-image/blob/master/package.json) it uses [puppeteer](https://github.com/puppeteer/puppeteer) so it needs chromium to works. The rendering engine must be Blink.

Please close this issue if it fixes it 👍

**Comment by stefanocudini** [comment]
it was not something so obvious maybe you should specify it in the readme

thank you

**Comment by frinyvonnick** [comment]
@stefanocudini would you be interested in opening a pull request to add it in the README?
