### ISSUE TITLE
Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by florinrelea** [frinyvonnick/node-html-to-image#75]
Hi! 
I am trying to install it on Ubuntu 18.04.5 LTS (GNU/Linux 5.3.0-1034-aws x86_64) and i received some dependencies errors from puppeteer. After installing the dependencies i received this error:
`ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported`

I solved this issue by adding the "--no-sandbox" argument:
`nodeHtmlToImage({ html, puppeteerArgs: { args: ['--no-sandbox'] } })`

Is there any other solution?

**Comment by frinyvonnick** [comment]
Hi @florinrelea 👋 

Thank you for posting this issue. node-html-to-image uses [puppeteer](https://github.com/puppeteer/puppeteer) under the hood. Here is an [issue](https://github.com/puppeteer/puppeteer/issues/3698) on their repository that is related to your problem. 

Please close this issue if it fixes it 👍

**Comment by florinrelea** [comment]
As i said,
`nodeHtmlToImage({ html, puppeteerArgs: { args: ['--no-sandbox'] } })`
 fixed it. I was just wondering if there is a better solution but it looks like this is the only one. 

Thanks for the puppeteer issue link!
