### ISSUE TITLE
Its possible to add in puppeteet args: ['--no-sandbox'] ??

### ISSUE THREAD

**Issue by BlakePro** [frinyvonnick/node-html-to-image#81]
First of all, great work.

**Comment by PavelKoroteev** [comment]
Hello, @BlakePro !
Why did you close the issue? Did you add args ? If yes, could you share your pass options ?

**Comment by BlakePro** [comment]
Sure, use something like that.

     let args = [
        '--disable-dev-shm-usage',
        '--enable-sync', '--enable-background-networking', '--no-sandbox', '--disable-setuid-sandbox',
        '--disable-gpu', '--renderer', '--no-service-autorun', '--no-experiments',
        '--no-default-browser-check', '--disable-webgl', '--disable-threaded-animation',
        '--disable-threaded-scrolling', '--disable-in-process-stack-traces', '--disable-histogram-customizer',
        '--disable-gl-extensions', '--disable-extensions', '--disable-composited-antialiasing',
        '--disable-canvas-aa', '--disable-3d-apis', '--disable-accelerated-2d-canvas',
        '--disable-accelerated-jpeg-decoding', '--disable-accelerated-mjpeg-decode', '--disable-app-list-dismiss-on-blur',
        '--disable-accelerated-video-decode', '--mute-audio',
        '--log-level=3',
        '--disable-infobars',
        '--disable-web-security',
        '--disable-site-isolation-trials',
        '--ignore-gpu-blacklist',
        '--ignore-certificate-errors',
        '--ignore-certificate-errors-spki-list',
        '--disable-default-apps',
        '--enable-features=NetworkService',
        '--no-first-run',
        '--no-zygote',
        '--unlimited-storage'
      ];

      let iimage = await nodeHtmlToImage({
        "encoding": "base64",
        "html": html,
        "puppeteerArgs": {"args": args}
      });

      console.log('data:image/png;base64,' + html_image);

**Comment by PavelKoroteev** [comment]
> Sure, use something like that.
> 
> ```
>  let args = [
>     '--disable-dev-shm-usage',
>     '--enable-sync', '--enable-background-networking', '--no-sandbox', '--disable-setuid-sandbox',
>     '--disable-gpu', '--renderer', '--no-service-autorun', '--no-experiments',
>     '--no-default-browser-check', '--disable-webgl', '--disable-threaded-animation',
>     '--disable-threaded-scrolling', '--disable-in-process-stack-traces', '--disable-histogram-customizer',
>     '--disable-gl-extensions', '--disable-extensions', '--disable-composited-antialiasing',
>     '--disable-canvas-aa', '--disable-3d-apis', '--disable-accelerated-2d-canvas',
>     '--disable-accelerated-jpeg-decoding', '--disable-accelerated-mjpeg-decode', '--disable-app-list-dismiss-on-blur',
>     '--disable-accelerated-video-decode', '--mute-audio',
>     '--log-level=3',
>     '--disable-infobars',
>     '--disable-web-security',
>     '--disable-site-isolation-trials',
>     '--ignore-gpu-blacklist',
>     '--ignore-certificate-errors',
>     '--ignore-certificate-errors-spki-list',
>     '--disable-default-apps',
>     '--enable-features=NetworkService',
>     '--no-first-run',
>     '--no-zygote',
>     '--unlimited-storage'
>   ];
> 
>   let iimage = await nodeHtmlToImage({
>     "encoding": "base64",
>     "html": html,
>     "puppeteerArgs": {"args": args}
>   });
> 
>   console.log('data:image/png;base64,' + html_image);
> ```

Thank you very much!
