### ISSUE TITLE
Handlebars sometimes escapes base64

### ISSUE THREAD

**Issue by Schroedingers-Hat** [frinyvonnick/node-html-to-image#89]
I was having some trouble with data url's in css. Turns out handlebars was escaping the last piece of my base64 data ass if it were html including a semicolon. Manually compiling and rendering with `noEscape: true` fixed it, but there's no way that I can see to pass in an options object for handlebar to use.

**Comment by frinyvonnick** [comment]
Hi @Schroedingers-Hat 👋 

Thank you for opening this issue 🙏  Do you want to open a pull request to add a property handlebarsArgs?

**Comment by frinyvonnick** [comment]
Without any new answer I close this issue. Feels free to reopen it 👍
