### ISSUE TITLE
Buffer() is deprecated

### ISSUE THREAD

**Issue by djebR** [frinyvonnick/node-html-to-image#9]
(node:3520) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by frinyvonnick** [comment]
Hi @djebR 👋 

Thank you for opening this issue. I'll try to guess what is your problem. I bet you try to import a locally stored images. @mrbjjackson made some improvements on the section [Dealing with images](https://github.com/frinyvonnick/node-html-to-image#dealing-with-images) to avoid this message. Does following this new implementation fix your issue?

**Comment by djebR** [comment]
The issue is avoided by adding the line:
const dataURI = 'data:image/jpeg;base64,' + base64Image

thanks for the reference.
