### ISSUE TITLE
Bump puppeteer to 3.0.4

### ISSUE THREAD

**Issue by mdlindsey** [frinyvonnick/node-html-to-image#91]
For those of us having [this issue](https://github.com/puppeteer/puppeteer/issues/5662) can we get a version bump of `pupeteer` from `3.0.0` to `3.0.4`?

**Comment by frinyvonnick** [comment]
Hi @mdlindsey 👋 

Thank you for opening this issue. Do you want to open a pull request that updates this package and see if all tests passes?

**Comment by MichaelJGW** [comment]
#113

**Comment by frinyvonnick** [comment]
This was released in [v3.2.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.0) 🚀

**Comment by mashwishi** [comment]
I'm using:
```json
		"node-html-to-image": "^3.2.0",
		"puppeteer": "^3.0.4"
```		
and still having problem

**Comment by sumitbajaj-tarento** [comment]
@frinyvonnick Please help with the issue

**Comment by frinyvonnick** [comment]
I just released [3.3.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.3.0) version which contain a feature to customise which puppeteer library node-html-to-image uses. It might help you making node-html-to-image work in a cloud context. Here is the documentation : https://github.com/frinyvonnick/node-html-to-image#using-different-puppeteer-libraries
