### ISSUE TITLE
Image Quality using defaultViewport argument to puppeteer?

### ISSUE THREAD

**Issue by Malikx-Alee** [frinyvonnick/node-html-to-image#92]
I want to improve the png image quality by passing the following puppeteer argument

```
defaultViewport: {
    deviceScaleFactor: 2
}
```

But i gives error. Any help how to pass this argument would be great help.

**Comment by jaredlomangino** [comment]
Also looking to solve this issue^

**Comment by Malikx-Alee** [comment]
@jaredlomangino , Width and Height is need to be added.  I solved it like this

![image](https://user-images.githubusercontent.com/28903531/106041689-f0ed2d80-60fd-11eb-9ebf-765f191bffb3.png)

**Comment by igor9silva** [comment]
Hi @Malikx-Alee, do I need `executablePath` to use `defaultViewport`? I'd like to use the default exec path.
