### ISSUE TITLE
Linking to script files

### ISSUE THREAD

**Issue by bna-ch** [frinyvonnick/node-html-to-image#93]
Hi, I just want to know if there is a way to link to static files I have in the public folder to html while generating images.
for I want to have <link href="path-to-file">. I have tried doing this, but no luck. Someone has any idea on how to do this?

**Comment by frinyvonnick** [comment]
Hi @bna-ch 👋 

Thank you for opening this issue. Can you share a piece of code that reproduce your issue, please?

**Comment by frinyvonnick** [comment]
I close this issue. Feel free to reopen it.
