### ISSUE TITLE
Issue Rendering CSS

### ISSUE THREAD

**Issue by mckay** [frinyvonnick/node-html-to-image#94]
I believe I have found an issue in which case HTML inside of the package cannot render correctly, but when in its own file can.

**Comment by frinyvonnick** [comment]
Hi @mckay 👋 

Thank you for opening this issue 🙏  Can you provide me more information to be able to reproduce you problem (code, screenshot, error stacks, ...)?

**Comment by frinyvonnick** [comment]
I close this issue. Feel free to reopen it.
