### ISSUE TITLE
Proper way to use external HTML file

### ISSUE THREAD

**Issue by yudy-chen** [frinyvonnick/node-html-to-image#96]
I am trying to use external HTML file, so far things work properly except for the font.

Below are the codes for the main program

```
const nodeHtmlToImage = require('node-html-to-image')
 
var getVar = require("./getVar.js")
const fs = require('fs')
var html_code = ""

html_code = fs.readFileSync('./app.html', 'utf8' , (err, data) => {
  if (err) {
    console.error(err)
    return
  }
  data
})
var appVars = new getVar();

nodeHtmlToImage({
  output: './image.png',
  html: html_code,
  content: { vars: appVars}
})
.then(() => console.log('The image was created successfully!'))
```

Below are the codes for the HTML
```

<html>
<head>
	
	<style>

		.div_name{
			background-color:{{vars.bg_color}};
			color:white;
		}	
		
		@font-face {
			font-family: 'slick';
			font-weight: normal;
			font-style: normal;
			src: url({{vars.raw_font}}) format('woff');
		}
	</style>
</head>
	<body>
		{{vars.raw_font}}
		<div class="div_name" >Hello {{vars.world}}!</div>
		<div style="font-family:'Times New Roman', Times, serif;">Hello {{vars.world}}!</div>
		<div style="font-family:'slick'">Hello my name is {{vars.world}}!</div>
		<img src={{vars.dog_img}} style='max-height:150px'></img>
	</body>
</html>

```

And here is the codes for getVar.js
```

const fs = require('fs');
function getVar() {
	this.world = function() {
		return 'world!';
	}
	this.dog_img = function(){
		const image = fs.readFileSync('./dog.png');
		const base64Image = new Buffer.from(image).toString('base64');
		const dataURI = 'data:image/jpeg;base64,' + base64Image
		return dataURI
		
	}
	this.new_font = function(){
		const font2base64 = require('node-font2base64')
		const _data = font2base64.encodeToDataUrlSync('./PottaOne-Regular.woff')
		return _data
	}
	this.bg_color = function(){
		return 'red'
	}
	this.raw_font = "data:application/font-woff;charset=utf-8;base64,d09GRgA ..."
};

module.exports = getVar;
```

Basically I would like to use the font from new_font and it doesn't work, so I am trying to use raw_font for testing and it doesn't work as well. And the `background-color:{{vars.bg_color}};` on that style works well

**Comment by frinyvonnick** [comment]
Hi @yudy-chen 👋 

Thank you for opening this issue 🙏  There are a few closed issue on the topic of font [here](https://github.com/frinyvonnick/node-html-to-image/issues?q=is%3Aissue+font+is%3Aclosed). Did you try the solution listed in them?

**Comment by yudy-chen** [comment]
Yes I tried [this](https://github.com/frinyvonnick/node-html-to-image/issues/72). It's working with hard coded base64 font, but it doesn't work using variable like I explain on the issue.

In the end I make it work to prepare the style outside of that HTML and on that HTML I include this string.

**Comment by frinyvonnick** [comment]
I don't if using interpolate functions in handlebars is recommended. Prepare variables outside seems more simple. Can I close the issue?

**Comment by yudy-chen** [comment]
Yes you can close it. Thank you
