### ISSUE TITLE
Alter Args is cluster in file index.js

### ISSUE THREAD

**Issue by EmersonGarrido** [frinyvonnick/node-html-to-image#97]
My application worked on site, but when it went to production on the ubuntu server, it was giving a sandbox error.

I made a brief change to the file by adding the following line
21 to 24:

`puppeteerOptions: { ...puppeteerArgs, headless: true, args: [
      '--no-sandbox',
      '--disable-setuid-sandbox'
      ] },
`
This code fixed the sandbox error problem.

**Comment by frinyvonnick** [comment]
Hi @EmersonGarrido 👋 

Thank you for opening this issue 🙏  I don't understand your problem. Why didn't you wrote your code like this:

```js
const nodeHtmlToImage = require('node-html-to-image')

nodeHtmlToImage({
  puppeteerArgs: { args: [ '--no-sandbox', '--disable-setuid-sandbox' ] },
  output: './image.png',
  html: `<html><body>Hello world!</body></html>`
})
  .then(() => console.log('The image was created successfully!'))
```

That's why `puppeteerArgs` is meant for.

**Comment by frinyvonnick** [comment]
I closed this issue. Feel free to reopen it.
