### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by XIIIcool** [frinyvonnick/node-html-to-image#98]
I have a problem when I create multiple images. My application has a timeline, and I convert comments into pictures. When there are several conversions in the tile, then there is a memory leak, and when there are more than 50 of them, the application generally hangs.

error:
(node:124106) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at process.addListener [as on] (events.js:406:10)
    at Function.addEventListener (/home/WebstormProjects/works/doc-exporter/node_modules/puppeteer/lib/helper.js:123:17)
    at BrowserRunner.start (/home/WebstormProjects/works/doc-exporter/node_modules/puppeteer/lib/Launcher.js:93:35)
    at ChromeLauncher.launch (/home/WebstormProjects/works/doc-exporter/node_modules/puppeteer/lib/Launcher.js:205:16)

```js
const docx = require("docx");
const {Paragraph, Media} = docx;
const docHelperFormat = require('../docHelperFormat');
const nodeHtmlToImage = require('node-html-to-image');
const sizeOf = require('image-size');

async function init(item, doc) {
    const arr = [];
    var eventText = '';
    arr.push(
        docHelperFormat.createRoleText('')
    )

    if (!item.parent) {

        eventText = `${item.author.fio} оставил(а) комментарий`;

    } else {

        eventText = `${item.author.fio} процитировал(а) комментарий`;

    }

    const puppeteerArgs = { args: [ '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-accelerated-2d-canvas', '--no-first-run', '--headless', '--no-zygote', '--disable-gpu' ], headless: true, ignoreHTTPSErrors: true };

    arr.push(docHelperFormat.createEventHeader(docHelperFormat.formattedDateFromTS(item.createdAt) + ' ' + eventText));

   const Image = await nodeHtmlToImage({
        html: item.content,
        puppeteerArgs // puppeteerArgs: { args: [ '--no-sandbox', '--disable-setuid-sandbox' ] },
    });

    let dimensions = sizeOf(Image);

    arr.push(
        new Paragraph(
            // docHelperFormat.createRoleText('')
            Media.addImage(doc, Image, dimensions.width, dimensions.height)
        )
    )

    return arr;

}


module.exports = {
    init
}
```

**Comment by frinyvonnick** [comment]
Hi @XIIIcool 👋 

Thank you for opening this issue. Can you share your environment versions (node, os, ...)?

**Comment by XIIIcool** [comment]
node v14.15.1
os ubuntu 20.04
Thank you for your prompt reply. Okay, I'll try to make pictures with one method.

**Comment by XIIIcool** [comment]
Bulk image creation solved the problem of memory leaks and application hang. But for some reason in the created pictures the html was not converted, but the code remained. And it would not be bad to transfer a unique identifier to the mass creation of images in the content, so that you can easily extract it.

`    async makeTicketEmailImages() {
        let content = [];
        
        this.ticketEmails.forEach((i) =>{
            content.push({
                content: i.content
            })
        })

        const images = await nodeHtmlToImage({
            html: '<html><body>{{content}}</body></html>',
            content: content
        })

        this.ticketEmails.map((val, index) => {
            this.ticketEmails[index].bufferImage = images[index]
            return val;
        })

    }`

![1](https://user-images.githubusercontent.com/7738545/107210125-c318ba80-6a14-11eb-954b-1f738f1899f4.png)

**Comment by frinyvonnick** [comment]
Handlebars seems to escape your html. Here is the [documentation](https://handlebarsjs.com/guide/expressions.html#html-escaping) about this.

**Comment by frinyvonnick** [comment]
There is a issue about mass creation ordering #85 and one about base64 being escaped that might be linked #89 🤔

**Comment by XIIIcool** [comment]
resolved problem, changed {{to {{{, thanks a lot for great support
