### ISSUE TITLE
Blurry image

### ISSUE THREAD

**Issue by AlessandroAries** [frinyvonnick/node-html-to-image#99]
When I just try a simple example like this:
```
nodeHtmlToImage({
        html: `<html><body>Hello world!</body></html>`,
        type: "png",
        output: "./image.png",
    });
```
I get a blurry image as output, any idea how this is possible?
![image](https://user-images.githubusercontent.com/15822086/107373119-756c8280-6ae6-11eb-902d-8634ec660f2f.png)

**Comment by frinyvonnick** [comment]
Hi @AlessandroAries 👋 

Thank you for opening this issue 🙏  You can try to change the quality in the [options](https://github.com/frinyvonnick/node-html-to-image#options) to improve it. Tell me if it is better after this 😄

**Comment by AlessandroAries** [comment]
> Hi @AlessandroAries 👋
> 
> Thank you for opening this issue 🙏 You can try to change the quality in the [options](https://github.com/frinyvonnick/node-html-to-image#options) to improve it. Tell me if it is better after this 😄

Hi, I already tried that with jpeg, but didn't work and for png it also doesn't work (also because thats not used occording to the documentation)

**Comment by YonatanHanan** [comment]
is there any solution? i have the same problem

**Comment by frinyvonnick** [comment]
You could try to set the [deviceScaleFactor](https://github.com/puppeteer/puppeteer/blob/v10.1.0/docs/api.md#puppeteerconnectoptions). You can pass options to puppeteer using **puppeteerArgs** property.

**Comment by frinyvonnick** [comment]
@AlessandroAries or @YonatanHanan did you try to set the [deviceScaleFactor](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerconnectoptions)?

**Comment by amihos** [comment]
Hi, I have the same issue. Can you please show me how to pass that option? 
will this work? puppeteerArgs: {'defaultViewport.deviceScaleFactor' : '1'},

**Comment by myoganugraha** [comment]
Hi, i tried using `defaultViewport.deviceScaleFactor`, but it seems doesn't works,
then i tried with 
```
puppeteerArgs: {
                'defaultViewport': {
                    'deviceScaleFactor': 2
                }
            }
```

it give me an error
`UnhandledPromiseRejectionWarning: Error: Unable to get browser page`,

any suggestion ? if i'm using `beforeScreenshot` parameter, it'll works but then it needs specific width and height value

**Comment by igor9silva** [comment]
Same as @myoganugraha.

**Comment by myoganugraha** [comment]
hi @igor9silva, my solution is using `beforeScreenshot` argument, to handle dynamic height of my document, i'm using 
```
const height = await page.evaluate(
          () => document.documentElement.offsetHeight
);
```

inside my `beforeScreenshot`, and here's full example

```
beforeScreenshot: async (page: any) => {
        const height = await page.evaluate(
          () => document.documentElement.offsetHeight
        );
        await page.setViewport({
          width: 375,
          height: height,
          deviceScaleFactor: 1.6
        });
      },
```

**Comment by igor9silva** [comment]
> hi @igor9silva, my solution is using `beforeScreenshot` argument, to handle dynamic height of my document, i'm using 
> 
> ```
> 
> const height = await page.evaluate(
> 
>           () => document.documentElement.offsetHeight
> 
> );
> 
> ```
> 
> 
> 
> inside my `beforeScreenshot`, and here's full example
> 
> 
> 
> ```
> 
> beforeScreenshot: async (page: any) => {
> 
>         const height = await page.evaluate(
> 
>           () => document.documentElement.offsetHeight
> 
>         );
> 
>         await page.setViewport({
> 
>           width: 375,
> 
>           height: height,
> 
>           deviceScaleFactor: 1.6
> 
>         });
> 
>       },
> 
> ```

Oh, very interesting, thanks for sharing!

**Comment by frinyvonnick** [comment]
Thank you @myoganugraha for providing the solution 👍 I close this issue since it seems to fix it 😄

**Comment by igor9silva** [comment]
@myoganugraha’s solution also worked for me, thanks!
